const orvalConfig = {
  api: {
    input: {
      target: "http://localhost:8000/api/schema",
    },
    output: {
      target: "api/",
      mode: "tags-split",
      client: "react-query",
      prettier: true,
      override: {
        header: (info: any): string =>
          `// @ts-nocheck\n\n/**\n * ${[
            `Auto Generated by orval`,
            `Do not edit manually.`,
            ...(info.title ? [`${info.title}`] : []),
            ...(info.description ? [`${info.description}`] : []),
          ].join("\n * ")}\n */\n\n`,
        mutator: {
          path: "./lib/axiosInstance.ts",
          name: "customAxios",
        },
        useNativeEnums: true,
      },
    },
  },
};

export default orvalConfig;
